version: "3.6"
services:
  node:
    build:
      context: .
      target: development
    environment:
      - ENV=/home/node/shell/ash.sh
      - PROJECT=eslint-config
    tty: true
    volumes:
      - shell:/home/node/shell
      - ./config:/home/node/config
      - ./source:/home/node/workspace/source
    working_dir: /home/node/workspace
volumes:
  shell:
    external: true
